version: '3'
# start by cleaning up old containers since logger will conflict
# docker-compose rm -f;docker-compose up
services:
  db:
    image: mysql:latest
    volumes:
      - ./resource/migration:/var/lib/mysql
    networks:
      - test_network
  api:
    build: .
    ports:
      - "8124:8085"
    networks:
      - test_network
    depends_on: #cho db start trc
      - db
networks:
    test_network:
      driver: bridge
