version: '3'
# start by cleaning up old containers since logger will conflict
# docker-compose rm -f;docker-compose up
services:
  db:
    image: mysql:latest
    volumes:
      - ./resource/migration:/var/lib/mysql
    networks:
      - backend
  redis:
    image: redis:5.0.7-alpine
    volumes:
      -
    networks:
      - backend
  api:
    build: .
    ports:
      - "8124:8085"
    networks:
      - backend
    depends_on: #cho db start trc
      - db
      - redis
networks:
  backend:
    driver: bridge
